package settings;

import cli.PlacedOrder;
import menu.DefaultFood;
import menu.Destination;
import menu.FoodItem;
import menu.Meal;
import org.w3c.dom.ranges.Range;

import java.io.*;
import java.util.*;

public class settings {

    ArrayList<Destination> map;
    Set<PlacedOrder> foods;
    List<FoodItem> meals;
    File settingsFile;

    private static settings single_instance = null;

    private settings(){
        map = new ArrayList<>();
        foods = new HashSet<>();
        meals = new ArrayList<>();

        // names = new ArrayList<>();
        try {
            //Names.txt was generated by Dominic Tarr
            settingsFile = new File("settings.txt"); //open the names file

            //Seed the arraylist with names in the file
            Scanner s = new Scanner(settingsFile);
            while(s.hasNext()) {
                String next = s.nextLine();
                if(next.contains("<d>")) {
                    //next.substring(next.indexOf(" "),next.length());
                    //Destinations.add();
                    String name;
                    int x, y;
                    double dist;

                    //For each line in the file
                    while (s.hasNextLine()) {
                        Scanner line = new Scanner(s.nextLine()); //Scanner for the given line

                        //Get the attributes from the file
                        name = line.next();
                        x = line.nextInt();
                        y = line.nextInt();
                        dist = line.nextDouble();

                        //Create a new destination
                        map.add(new Destination(name, x, y, dist));
                        line.close();
                    }
                }
            }
            s.close();

        } catch (Exception e) {
            System.out.println((e.getMessage()));
        }
    }
    //Singleton creator
    public static settings getInstance() {
        if (single_instance == null) {
            single_instance = new settings();
        }
        return single_instance;
    }

    public void exportSimSettings(){

    }

    public void importSimSettings(){

    }

    public void addMapPoint(int x, int y, float dist){

    }

    public void removeMapPoint(int x, int y){

    }

    public void editMapPoint(int x, int y, float dist){

    }

    public void exportMap(){

    }

    public void importMap(){

    }

    public boolean verifyMap(){

        return false;
    }

}
